<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.matrix</groupId>
    <artifactId>matrix</artifactId>
    <version>1.0.1</version>
    <packaging>pom</packaging>

    <name>Matrix Parent</name>
    <description>Matrix - Only supports Deepseek</description>

    <modules>
        <module>matrix-client</module>
        <module>matrix-cloud</module>
        <module>matrix-local</module>
    </modules>

</project>
